site_name: Profile Explorer
use_directory_urls: false
nav:
  - Getting started:
    - Introduction: intro.md
    - Loading a trace: trace-loading.md
    - Recording a trace: trace-recording.md
    - Profiling UI overview: profiling-ui.md
  - Profiling panels and views:
    - Summary panel: summary-panel.md
    - Assembly view: assembly-view.md
    - Source File panel: source-panel.md
    - Flame Graph panel: flame-graph-panel.md
    - Timeline panel: timeline-panel.md
    - Call Tree panel: call-tree-panel.md
    - Caller/Callee panel: caller-panel.md
  - Additional functionality:
    - Workspaces: workspaces.md
    - Previewe popups: workspaces.md
    - Viewing multiple functions: workspaces.md
    - Viewing indirect calls: workspaces.md
  - Demos: demos.md
theme:
  name: 'material'
  font: false
  palette:
    primary: 'blue'
    accent: 'white'
  features:
    - navigation.expand
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences