site_name: Profile Explorer
use_directory_urls: false
nav:
  - Introduction: intro.md
  - Getting started:
    - Profiling UI overview: profiling-ui.md
    - Video Demos: demos.md
    - About: about.md
  - Trace loading and recording:
    - Loading a trace: trace-loading.md
    - Recording a trace: trace-recording.md
    - Trace overview report: trace-overview.md
  - Trace profile views:
    - Summary view: summary-panel.md
    - Flame Graph view: flame-graph-panel.md
    - Timeline view: timeline-panel.md
    - Call Tree view: call-tree-panel.md
    - Caller/Callee view: caller-panel.md
  - Function profile views:
    - Assembly view: assembly-view.md
    - Source File view: source-panel.md
    - Flow Graph view: flow-graph-panel.md
  - Additional functionality:
    - Function/module marking: marking.md
    - Preview popups: workspaces.md
    - Working with multiple functions: workspaces.md
    - Viewing function instances: function-instances.md
    - Workspaces: workspaces.md
    - Application options: options.md
    - Rust support: options.md
theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.top
    - header.autohide
    - navigation.footer
extra:
  generator: false
extra_css:
  - style.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true